spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/textjava?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  #redis的服务器所在的ip地址
  redis:
    host: 127.0.0.1
    #redis的端口号
    port: 6379

#mybatis-plus
mybatis-plus:
# 如果是放在src/main/java目录下 classpath:/com/*/*/mapper/*Mapper.xml
# 如果是放在resource目录 classpath:/mapper/**.xml
  mapper-locations: classpath:/mappers/**.xml

server:
  port: 7077

# spring boot actuator监控 配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#class
studentClass: /studentClass