spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/textjava?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  #redis的服务器所在的ip地址
  redis:
    host: 127.0.0.1
    #redis的端口号
    port: 6379

#mybatis-plus
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/*/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/**.xml
  mapper-locations: classpath:/mappers/**.xml
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 7077

# spring boot actuator监控 配置
management:
  endpoints:
    web:
      # 开启暴露所有的端点信息
      exposure:
        include: "*"
      # 调整端点的前缀路径为/
      base-path: /
  endpoint:
    health:
      show-details: always #显示具体健康信息 默认不会显示详细信息
    httptrace:
      enabled: true #启用httptrace端点
  server:
    port: 8088
  security:
    user:
      name: ch
      password: 123
      roles: ADMIN



#class
studentClass: /studentClass